name: Sonic Phantoms
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45851
title: 'sonic phantoms '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5524870054796338
purpose: []
