name: Sonic Phantoms
favicon: null
layout_spectrum: 0.8856531956698745
typography_spectrum: 0.6558379181660712
title: 'sonic phantoms '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09611616795882583
  lightness: 0.4943115212954581
  saturation: 0.5255073439329863
  rhythmicContrast: 0.5524870054796338
purpose: []
